services:
  - type: web
    runtime: python
    name: Contacts App
    repo: https://github.com/Timbotenbo101/PythonApp # Default: Repo containing render.yaml
    region: frankfurt # Default: oregon
    plan: free    # Default: starter
    branch: main      # Default: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project:app
    autoDeploy: true # Disable automatic deploys
    